// @ifndef PLAYER
;var Fire = Fire || {};
(function (Fire) {
// @endif

// @ifdef DEV
    var __TESTONLY__ = {};
    Fire.__TESTONLY__ = __TESTONLY__;
// @endif

// @ifndef PLAYER
    var FObject = Fire.FObject;
    var HashObject = Fire.HashObject;
    var Asset = Fire.Asset;
    var Vec2 = Fire.Vec2;
    var Matrix23 = Fire.Matrix23;
    var Rect = Fire.Rect;
    var Color = Fire.Color;
    var Texture = Fire.Texture;
    var Sprite = Fire.Sprite;
    var Atlas = Fire.Atlas;
    //var FontInfo = Fire.FontInfo;
// @endif

    // The code below is generated by script automatically:
    // <%=contents%>
    // end of generated code

})(Fire || (Fire = {}));

if (typeof module !== "undefined" && module) {
    module.exports = Fire;
}
else if (typeof define === "function" && define && define.amd) {
    define([], function() {
        return Fire;
    });
}
